/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Classes.Ambulancias;
import Classes.Complejo_Hospitalario;
import Classes.Grafo;
import Classes.Hilo;
import Classes.Paramedicos;
import grph.algo.distance.DistanceMatrix;
import grph.algo.traversal.SearchResult;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel A. Ardon E
 */
public class eHospital extends javax.swing.JFrame {

    /**
     * Creates new form eHospital
     */
    public class Imagen extends javax.swing.JPanel {

        String path;

        public Imagen(String path) {
            this.setSize(jpanel_entrada.getWidth(), jpanel_entrada.getHeight());
            this.path = path;
        }

        public void paint(Graphics grafico) {
            Dimension height = getSize();
            ImageIcon Img = new ImageIcon(getClass().getResource(path));
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    public eHospital() {
        initComponents();
        jpanel_entrada.setSize(this.getWidth(), this.getHeight());
        this.setResizable(false);
        this.setTitle("eHospital");
        Imagen Imagen = new Imagen("/Images/entrada.jpg");
        jpanel_entrada.add(Imagen);
        jpanel_entrada.repaint();
        ImageIcon complejo = new ImageIcon(new ImageIcon("complejo.png").getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        ImageIcon paramedico = new ImageIcon(new ImageIcon("paramedico.jpg").getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        ImageIcon ambulancias = new ImageIcon(new ImageIcon("ambulancia.jpg").getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        ImageIcon coneccion = new ImageIcon(new ImageIcon("conceccion.jpg").getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        jbotton_complejo.setIcon(complejo);
        jbotton_paramedico.setIcon(paramedico);
        jbotton_ambulancia.setIcon(ambulancias);
        jbotton_coneccion.setIcon(coneccion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Complejo = new javax.swing.JFrame();
        jpanel_complejo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        agregar_complejo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        complejo_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        complejo_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        complejo_paramedicos = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        complejo_ambulancias = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        complejo_ranking = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jb_paramedicos = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jb_ambulancia = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        eliminar_complejo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        combo_eliminarcomplejo = new javax.swing.JComboBox();
        Paramedicos = new javax.swing.JFrame();
        jpanel_paramedicos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        eliminar_paramedico = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        combo_eliminarparamedico = new javax.swing.JComboBox();
        agregar_paramedico = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        paramedico_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        paramedico_ranking = new javax.swing.JComboBox();
        paramedico_id = new javax.swing.JFormattedTextField();
        paramedico_edad = new javax.swing.JSpinner();
        Ambulancia = new javax.swing.JFrame();
        jpanel_ambulancia = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        eliminar_ambulancia = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        combo_eliminarambulancias = new javax.swing.JComboBox();
        agregar_ambulancia = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ambulancia_placa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ambulancia_año = new javax.swing.JFormattedTextField();
        ambulancia_velocidad = new javax.swing.JSpinner();
        Conecciones = new javax.swing.JFrame();
        jpanel_coneccion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        agregar_coneccion = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        inicio = new javax.swing.JComboBox();
        end = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a_otrolado = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        otro_lado = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        peso_a = new javax.swing.JTextField();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        floyd_coneccion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_floyd = new javax.swing.JTextArea();
        emergencia_coneccion = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        centro_hos = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        lugar = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        emergencia_ranking = new javax.swing.JComboBox();
        jpanel_entrada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbotton_complejo = new javax.swing.JButton();
        jbotton_paramedico = new javax.swing.JButton();
        jbotton_ambulancia = new javax.swing.JButton();
        jbotton_coneccion = new javax.swing.JButton();

        Complejo.setPreferredSize(new java.awt.Dimension(1008, 589));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Acciones que puede realizar:");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Agregar Complejo Hospitalario");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox2.setText("Eliminar Complejo Hospitalario");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre del Complejo:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Capacidad maxima de paramedicos:");

        complejo_paramedicos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Capacidad maxima de ambulancias:");

        complejo_ambulancias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel7.setText("Ranking de Emergencias:");

        complejo_ranking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel16.setText("Paramedicos Disponibles:");

        jLabel19.setText("Ambulancias Disponible:");

        jButton7.setText("Agregar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregar_complejoLayout = new javax.swing.GroupLayout(agregar_complejo);
        agregar_complejo.setLayout(agregar_complejoLayout);
        agregar_complejoLayout.setHorizontalGroup(
            agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_complejoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_complejoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(complejo_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregar_complejoLayout.createSequentialGroup()
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(complejo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(complejo_direccion))))
                .addGap(49, 49, 49)
                .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_complejoLayout.createSequentialGroup()
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(complejo_ambulancias)
                            .addComponent(complejo_ranking, 0, 151, Short.MAX_VALUE)))
                    .addGroup(agregar_complejoLayout.createSequentialGroup()
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_ambulancia, 0, 200, Short.MAX_VALUE)
                            .addComponent(jb_paramedicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregar_complejoLayout.setVerticalGroup(
            agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_complejoLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(complejo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(complejo_ambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(complejo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(complejo_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jb_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(23, 23, 23)
                .addGroup(agregar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(complejo_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jb_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminar_complejoLayout = new javax.swing.GroupLayout(eliminar_complejo);
        eliminar_complejo.setLayout(eliminar_complejoLayout);
        eliminar_complejoLayout.setHorizontalGroup(
            eliminar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminar_complejoLayout.createSequentialGroup()
                .addGroup(eliminar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminar_complejoLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(combo_eliminarcomplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminar_complejoLayout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminar_complejoLayout.setVerticalGroup(
            eliminar_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_complejoLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(combo_eliminarcomplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jButton2)
                .addGap(187, 187, 187))
        );

        javax.swing.GroupLayout jpanel_complejoLayout = new javax.swing.GroupLayout(jpanel_complejo);
        jpanel_complejo.setLayout(jpanel_complejoLayout);
        jpanel_complejoLayout.setHorizontalGroup(
            jpanel_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_complejoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_complejoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregar_complejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpanel_complejoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminar_complejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanel_complejoLayout.setVerticalGroup(
            jpanel_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_complejoLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jpanel_complejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar_complejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_complejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ComplejoLayout = new javax.swing.GroupLayout(Complejo.getContentPane());
        Complejo.getContentPane().setLayout(ComplejoLayout);
        ComplejoLayout.setHorizontalGroup(
            ComplejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_complejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ComplejoLayout.setVerticalGroup(
            ComplejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_complejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Acciones que puede realizar: ");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox3.setText("Agregar Paramedico");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox4.setText("Eliminar Paramedico");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_paramedicosLayout = new javax.swing.GroupLayout(jpanel_paramedicos);
        jpanel_paramedicos.setLayout(jpanel_paramedicosLayout);
        jpanel_paramedicosLayout.setHorizontalGroup(
            jpanel_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_paramedicosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jpanel_paramedicosLayout.setVerticalGroup(
            jpanel_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_paramedicosLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jpanel_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        jButton4.setText("ELIMINAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminar_paramedicoLayout = new javax.swing.GroupLayout(eliminar_paramedico);
        eliminar_paramedico.setLayout(eliminar_paramedicoLayout);
        eliminar_paramedicoLayout.setHorizontalGroup(
            eliminar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_paramedicoLayout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(combo_eliminarparamedico, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(eliminar_paramedicoLayout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminar_paramedicoLayout.setVerticalGroup(
            eliminar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_paramedicoLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(combo_eliminarparamedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton4)
                .addGap(140, 140, 140))
        );

        jLabel8.setText("Nombre del Paramedico:");

        jLabel9.setText("ID");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Edad");

        jLabel12.setText("Ranking de Emergencias:");

        paramedico_ranking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        try {
            paramedico_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        paramedico_edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, 70, 1));

        javax.swing.GroupLayout agregar_paramedicoLayout = new javax.swing.GroupLayout(agregar_paramedico);
        agregar_paramedico.setLayout(agregar_paramedicoLayout);
        agregar_paramedicoLayout.setHorizontalGroup(
            agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregar_paramedicoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paramedico_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(paramedico_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(agregar_paramedicoLayout.createSequentialGroup()
                        .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paramedico_ranking, 0, 151, Short.MAX_VALUE)
                            .addComponent(paramedico_edad))))
                .addGap(269, 269, 269))
        );
        agregar_paramedicoLayout.setVerticalGroup(
            agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_paramedicoLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(paramedico_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(paramedico_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(agregar_paramedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(paramedico_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramedico_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout ParamedicosLayout = new javax.swing.GroupLayout(Paramedicos.getContentPane());
        Paramedicos.getContentPane().setLayout(ParamedicosLayout);
        ParamedicosLayout.setHorizontalGroup(
            ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ParamedicosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(eliminar_paramedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ParamedicosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(agregar_paramedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ParamedicosLayout.setVerticalGroup(
            ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_paramedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParamedicosLayout.createSequentialGroup()
                    .addContainerGap(169, Short.MAX_VALUE)
                    .addComponent(eliminar_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
            .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParamedicosLayout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(agregar_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("Acciones que se puede realizar:");

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox6.setText("Agregar Ambulancia");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox7.setText("Eliminar Ambulancia");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jButton6.setText("ELIMINAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminar_ambulanciaLayout = new javax.swing.GroupLayout(eliminar_ambulancia);
        eliminar_ambulancia.setLayout(eliminar_ambulanciaLayout);
        eliminar_ambulanciaLayout.setHorizontalGroup(
            eliminar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminar_ambulanciaLayout.createSequentialGroup()
                .addGroup(eliminar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminar_ambulanciaLayout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jButton6))
                    .addGroup(eliminar_ambulanciaLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(combo_eliminarambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        eliminar_ambulanciaLayout.setVerticalGroup(
            eliminar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_ambulanciaLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(combo_eliminarambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton6)
                .addGap(74, 74, 74))
        );

        jLabel14.setText("Placa de Ambulancia:");

        jLabel15.setText("Velocidad Maxima");

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel17.setText("Año");

        ambulancia_año.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        ambulancia_velocidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));

        javax.swing.GroupLayout agregar_ambulanciaLayout = new javax.swing.GroupLayout(agregar_ambulancia);
        agregar_ambulancia.setLayout(agregar_ambulanciaLayout);
        agregar_ambulanciaLayout.setHorizontalGroup(
            agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregar_ambulanciaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_ambulanciaLayout.createSequentialGroup()
                        .addComponent(ambulancia_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agregar_ambulanciaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(ambulancia_año, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5))
                        .addGap(370, 370, 370))
                    .addGroup(agregar_ambulanciaLayout.createSequentialGroup()
                        .addComponent(ambulancia_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        agregar_ambulanciaLayout.setVerticalGroup(
            agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_ambulanciaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ambulancia_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(ambulancia_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(agregar_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ambulancia_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jpanel_ambulanciaLayout = new javax.swing.GroupLayout(jpanel_ambulancia);
        jpanel_ambulancia.setLayout(jpanel_ambulanciaLayout);
        jpanel_ambulanciaLayout.setHorizontalGroup(
            jpanel_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ambulanciaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox6)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(eliminar_ambulancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanel_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanel_ambulanciaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(agregar_ambulancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpanel_ambulanciaLayout.setVerticalGroup(
            jpanel_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ambulanciaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jpanel_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7))
                .addGap(229, 229, 229)
                .addComponent(eliminar_ambulancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpanel_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanel_ambulanciaLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(agregar_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout AmbulanciaLayout = new javax.swing.GroupLayout(Ambulancia.getContentPane());
        Ambulancia.getContentPane().setLayout(AmbulanciaLayout);
        AmbulanciaLayout.setHorizontalGroup(
            AmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(AmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AmbulanciaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanel_ambulancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        AmbulanciaLayout.setVerticalGroup(
            AmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(AmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AmbulanciaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanel_ambulancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Acciones que puede realizar:");

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox5.setText("Agregar conecciones");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox8.setText("Ver Mapa");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jLabel20.setText("De:");

        jLabel21.setText("A");

        jButton9.setText("Conectar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel22.setText("Peso:");

        jLabel23.setText("Centros Hospitalarios");

        jLabel24.setText("Ubicacion Distinta");

        jLabel25.setText("De:");

        jLabel26.setText("A:");

        jButton10.setText("Conectar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel27.setText("Peso:");

        javax.swing.GroupLayout agregar_coneccionLayout = new javax.swing.GroupLayout(agregar_coneccion);
        agregar_coneccion.setLayout(agregar_coneccionLayout);
        agregar_coneccionLayout.setHorizontalGroup(
            agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_coneccionLayout.createSequentialGroup()
                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_coneccionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(agregar_coneccionLayout.createSequentialGroup()
                                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)))
                            .addGroup(agregar_coneccionLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(peso)))
                        .addGap(92, 92, 92)
                        .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(agregar_coneccionLayout.createSequentialGroup()
                                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25))
                                .addGap(27, 27, 27)
                                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel24)
                                    .addComponent(a_otrolado)
                                    .addComponent(otro_lado, 0, 165, Short.MAX_VALUE)))
                            .addGroup(agregar_coneccionLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(peso_a))))
                    .addGroup(agregar_coneccionLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton9)
                        .addGap(171, 171, 171)
                        .addComponent(jButton10)))
                .addContainerGap(725, Short.MAX_VALUE))
        );
        agregar_coneccionLayout.setVerticalGroup(
            agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_coneccionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(42, 42, 42)
                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(otro_lado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(a_otrolado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(peso_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(agregar_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox9.setText("Floyd");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox10.setText("Emergencias");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_coneccionLayout = new javax.swing.GroupLayout(jpanel_coneccion);
        jpanel_coneccion.setLayout(jpanel_coneccionLayout);
        jpanel_coneccionLayout.setHorizontalGroup(
            jpanel_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_coneccionLayout.createSequentialGroup()
                .addGroup(jpanel_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_coneccionLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(jCheckBox5)
                        .addGap(46, 46, 46)
                        .addComponent(jCheckBox8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9)
                        .addGap(39, 39, 39)
                        .addComponent(jCheckBox10))
                    .addGroup(jpanel_coneccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregar_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_coneccionLayout.setVerticalGroup(
            jpanel_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_coneccionLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jpanel_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox8)
                        .addComponent(jCheckBox9)
                        .addComponent(jCheckBox10))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(agregar_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txt_floyd.setColumns(20);
        txt_floyd.setRows(5);
        jScrollPane1.setViewportView(txt_floyd);

        javax.swing.GroupLayout floyd_coneccionLayout = new javax.swing.GroupLayout(floyd_coneccion);
        floyd_coneccion.setLayout(floyd_coneccionLayout);
        floyd_coneccionLayout.setHorizontalGroup(
            floyd_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floyd_coneccionLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        floyd_coneccionLayout.setVerticalGroup(
            floyd_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floyd_coneccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel28.setText("Centro Hospitalario:");

        jLabel29.setText("Lugar:");

        jButton11.setText("EMERGENCIA");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel30.setText("Ranking:");

        emergencia_ranking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        javax.swing.GroupLayout emergencia_coneccionLayout = new javax.swing.GroupLayout(emergencia_coneccion);
        emergencia_coneccion.setLayout(emergencia_coneccionLayout);
        emergencia_coneccionLayout.setHorizontalGroup(
            emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emergencia_coneccionLayout.createSequentialGroup()
                .addGroup(emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emergencia_coneccionLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(53, 53, 53)
                        .addGroup(emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(centro_hos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lugar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emergencia_ranking, 0, 181, Short.MAX_VALUE)))
                    .addGroup(emergencia_coneccionLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jButton11)))
                .addContainerGap(534, Short.MAX_VALUE))
        );
        emergencia_coneccionLayout.setVerticalGroup(
            emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emergencia_coneccionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(centro_hos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(emergencia_coneccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(emergencia_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton11)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ConeccionesLayout = new javax.swing.GroupLayout(Conecciones.getContentPane());
        Conecciones.getContentPane().setLayout(ConeccionesLayout);
        ConeccionesLayout.setHorizontalGroup(
            ConeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConeccionesLayout.createSequentialGroup()
                .addComponent(jpanel_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(ConeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ConeccionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(floyd_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
            .addGroup(ConeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ConeccionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(emergencia_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ConeccionesLayout.setVerticalGroup(
            ConeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConeccionesLayout.createSequentialGroup()
                .addComponent(jpanel_coneccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ConeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConeccionesLayout.createSequentialGroup()
                    .addContainerGap(193, Short.MAX_VALUE)
                    .addComponent(floyd_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(ConeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ConeccionesLayout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(emergencia_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("eHospital");

        jbotton_complejo.setBorder(javax.swing.BorderFactory.createTitledBorder("Complejo Hospitalario"));
        jbotton_complejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotton_complejoActionPerformed(evt);
            }
        });

        jbotton_paramedico.setBorder(javax.swing.BorderFactory.createTitledBorder("Paramedicos"));
        jbotton_paramedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotton_paramedicoActionPerformed(evt);
            }
        });

        jbotton_ambulancia.setBorder(javax.swing.BorderFactory.createTitledBorder("Ambulancias"));
        jbotton_ambulancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotton_ambulanciaActionPerformed(evt);
            }
        });

        jbotton_coneccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Union"));
        jbotton_coneccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotton_coneccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_entradaLayout = new javax.swing.GroupLayout(jpanel_entrada);
        jpanel_entrada.setLayout(jpanel_entradaLayout);
        jpanel_entradaLayout.setHorizontalGroup(
            jpanel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_entradaLayout.createSequentialGroup()
                .addGroup(jpanel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_entradaLayout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel1))
                    .addGroup(jpanel_entradaLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jpanel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_entradaLayout.createSequentialGroup()
                                .addComponent(jbotton_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbotton_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanel_entradaLayout.createSequentialGroup()
                                .addComponent(jbotton_complejo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                                .addComponent(jbotton_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(191, 191, 191))
        );
        jpanel_entradaLayout.setVerticalGroup(
            jpanel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_entradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_entradaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbotton_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_entradaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addGroup(jpanel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbotton_complejo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbotton_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jbotton_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbotton_complejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotton_complejoActionPerformed
        // TODO add your handling code here:
        jbotton_complejo.setEnabled(false);
        Complejo.setVisible(true);
        Complejo.setTitle("Complejos Hospitalarios");
        Complejo.pack();
        Complejo.setResizable(false);
        Imagen Imagen = new Imagen("/Images/complejojp.jpg");
        jpanel_complejo.add(Imagen);
        jpanel_complejo.repaint();
        agregar_complejo.setVisible(false);
        eliminar_complejo.setVisible(false);
        jbotton_complejo.setEnabled(true);
    }//GEN-LAST:event_jbotton_complejoActionPerformed

    private void jbotton_paramedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotton_paramedicoActionPerformed
        // TODO add your handling code here:
        jbotton_paramedico.setEnabled(false);
        Paramedicos.setVisible(true);
        Paramedicos.setTitle("Paramedicos");
        Paramedicos.pack();
        Paramedicos.setResizable(false);
        Imagen Imagen = new Imagen("/Images/paramedico_traje.jpg");
        jpanel_paramedicos.add(Imagen);
        jpanel_paramedicos.repaint();
        agregar_paramedico.setVisible(false);
        eliminar_paramedico.setVisible(false);
        jbotton_paramedico.setEnabled(true);

    }//GEN-LAST:event_jbotton_paramedicoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected() == true) {
            agregar_complejo.setVisible(true);
            eliminar_complejo.setVisible(false);
        } else {
            agregar_complejo.setVisible(false);
            eliminar_complejo.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected() == true) {
            agregar_complejo.setVisible(false);
            eliminar_complejo.setVisible(true);
        } else {
            agregar_complejo.setVisible(false);
            eliminar_complejo.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean is = false;
        if (complejo_hospitalario.isEmpty()) {
            Complejo_Hospitalario complejo = new Complejo_Hospitalario(complejo_nombre.getText(), complejo_direccion.getText(), Integer.parseInt(complejo_paramedicos.getValue().toString()), Integer.parseInt(complejo_ambulancias.getValue().toString()), complejo_ranking.getSelectedItem().toString(), temp_paramedico, temp_ambulancia);
            complejo_hospitalario.add(complejo);
            JOptionPane.showMessageDialog(jpanel_complejo, "Se agrego correctamente", "Completado", WIDTH);
            grafo.addNodos(numero);
            grafo.setNombreNodo(numero, complejo_nombre.getText());
            numero++;
            is = true;
        } else {
            for (int i = 0; i < complejo_hospitalario.size(); i++) {
                if (complejo_hospitalario.get(i).getNombre().contentEquals(complejo_nombre.getText())) {
                    is = true;
                    JOptionPane.showMessageDialog(jpanel_complejo, "NO se puede agregar un Complejo que ya existe", "Error Complejo", WIDTH);
                }
            }
        }
        if (!is) {
            Complejo_Hospitalario complejo = new Complejo_Hospitalario(complejo_nombre.getText(), complejo_direccion.getText(), Integer.parseInt(complejo_paramedicos.getValue().toString()), Integer.parseInt(complejo_ambulancias.getValue().toString()), complejo_ranking.getSelectedItem().toString(), temp_paramedico, temp_ambulancia);
            complejo_hospitalario.add(complejo);
            JOptionPane.showMessageDialog(jpanel_complejo, "Se agrego correctamente", "Completado", WIDTH);
            grafo.addNodos(numero);
            grafo.setNombreNodo(numero, complejo_nombre.getText());
            numero++;
        }

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < complejo_hospitalario.size(); i++) {
            model.addElement(complejo_hospitalario.get(i));
        }
        combo_eliminarcomplejo.setModel(model);
        centro_hos.setModel(model);

        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        nodo = grafo.getNodos();
        for (int i = 0; i < nodo.length + 1; i++) {
            model1.addElement(grafo.getNombreNodo(i));
            model2.addElement(grafo.getNombreNodo(i));
            model3.addElement(grafo.getNombreNodo(i));

        }
        inicio.setModel(model1);
        end.setModel(model2);
        otro_lado.setModel(model3);
        System.out.println(nodo.length + "lsita nodo" + numero + "numero");
        temp_ambulancia = new ArrayList();
        temp_paramedico = new ArrayList();
        complejo_ambulancias.setValue(1);
        complejo_paramedicos.setValue(1);
        complejo_nombre.setText("");
        complejo_direccion.setText("");
        for (int i = 0; i < complejo_hospitalario.size(); i++) {
            System.out.println(complejo_hospitalario.get(i).toString() + "iter" + i);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int reps = JOptionPane.showConfirmDialog(jpanel_complejo, "Desea eliminar este complejo?", " Eliminar", WIDTH);
        if (reps == 0) {
            complejo_hospitalario.remove(combo_eliminarcomplejo.getSelectedIndex());
            JOptionPane.showMessageDialog(jpanel_complejo, "Se elimino correctamente.", "Eliminado", reps);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (int i = 0; i < complejo_hospitalario.size(); i++) {
                model.addElement(complejo_hospitalario.get(i));
            }
            combo_eliminarcomplejo.setModel(model);
            centro_hos.setModel(model);
            DefaultComboBoxModel model1 = new DefaultComboBoxModel();
            nodo = grafo.getNodos();
            for (int i = 0; i < nodo.length; i++) {
                model1.addElement(grafo.getNombreNodo(i));
            }
            inicio.setModel(model1);
            end.setModel(model1);
            otro_lado.setModel(model1);
        } else {
            JOptionPane.showMessageDialog(jpanel_complejo, "No se elimino.", "Sin eliminar", reps);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int reps = JOptionPane.showConfirmDialog(jpanel_paramedicos, "Desea eliminar este complejo?", " Eliminar", WIDTH);
        if (reps == 0) {
            paramedicos.remove(combo_eliminarparamedico.getSelectedIndex());
            JOptionPane.showMessageDialog(jpanel_paramedicos, "Se elimino correctamente.", "Eliminado", reps);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (int i = 0; i < paramedicos.size(); i++) {
                model.addElement(paramedicos.get(i));
            }
            combo_eliminarparamedico.setModel(model);
        } else {
            JOptionPane.showMessageDialog(jpanel_paramedicos, "No se elimino.", "Sin eliminar", reps);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean is = false;
        if (paramedicos.isEmpty()) {
            Paramedicos paramedico = new Paramedicos(paramedico_nombre.getText(), Integer.parseInt(paramedico_edad.getValue().toString()), paramedico_id.getText(), paramedico_ranking.getSelectedItem().toString());
            paramedicos.add(paramedico);
            JOptionPane.showMessageDialog(jpanel_paramedicos, "Se agrego correctamente", "Completado", WIDTH);
            is = true;
        } else {
            for (int i = 0; i < paramedicos.size(); i++) {
                if (paramedicos.get(i).getNombre_completo().contentEquals(paramedico_nombre.getText())) {
                    is = true;
                    JOptionPane.showMessageDialog(jpanel_paramedicos, "NO se puede agregar al Paramedico porque ya existe", "Error Paramedico", WIDTH);
                }
            }
        }
        if (!is) {
            Paramedicos paramedico = new Paramedicos(paramedico_nombre.getText(), Integer.parseInt(paramedico_edad.getValue().toString()), paramedico_id.getText(), paramedico_ranking.getSelectedItem().toString());
            paramedicos.add(paramedico);
            JOptionPane.showMessageDialog(jpanel_paramedicos, "Se agrego correctamente", "Completado", WIDTH);
        }

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < paramedicos.size(); i++) {
            model.addElement(paramedicos.get(i));
        }
        combo_eliminarparamedico.setModel(model);
        jb_paramedicos.setModel(model);

        paramedico_edad.setValue(18);
        paramedico_nombre.setText("");
        paramedico_id.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox3.isSelected() == true) {
            agregar_paramedico.setVisible(true);
            eliminar_paramedico.setVisible(false);
        } else {
            agregar_paramedico.setVisible(false);
            eliminar_paramedico.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected() == true) {
            agregar_paramedico.setVisible(false);
            eliminar_paramedico.setVisible(true);
        } else {
            agregar_paramedico.setVisible(false);
            eliminar_paramedico.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jbotton_ambulanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotton_ambulanciaActionPerformed
        // TODO add your handling code here:
        jbotton_ambulancia.setEnabled(false);
        Ambulancia.setVisible(true);
        Ambulancia.setTitle("Ambulancia");
        Ambulancia.pack();
        Ambulancia.setResizable(false);
        Imagen Imagen = new Imagen("/Images/ambulancia_interior.jpg");
        jpanel_ambulancia.add(Imagen);
        jpanel_ambulancia.repaint();
        agregar_ambulancia.setVisible(false);
        eliminar_ambulancia.setVisible(false);
        jbotton_ambulancia.setEnabled(true);
    }//GEN-LAST:event_jbotton_ambulanciaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        boolean is = false;
        if (ambulancia.isEmpty()) {
            Ambulancias ambulancias = new Ambulancias(ambulancia_placa.getText(), ambulancia_año.getText(), Integer.parseInt(ambulancia_velocidad.getValue().toString()));
            ambulancia.add(ambulancias);
            JOptionPane.showMessageDialog(jpanel_ambulancia, "Se agrego correctamente", "Completado", WIDTH);
            is = true;
        } else {
            for (int i = 0; i < ambulancia.size(); i++) {
                if (ambulancia.get(i).getPlaca().contentEquals(ambulancia_placa.getText())) {
                    is = true;
                    JOptionPane.showMessageDialog(jpanel_ambulancia, "NO se puede agregar la Ambulanccia porque ya existe", "Error Paramedico", WIDTH);
                }
            }
        }
        if (!is) {
            Ambulancias ambulancias = new Ambulancias(ambulancia_placa.getText(), ambulancia_año.getText(), Integer.parseInt(ambulancia_velocidad.getValue().toString()));
            ambulancia.add(ambulancias);
            JOptionPane.showMessageDialog(jpanel_ambulancia, "Se agrego correctamente", "Completado", WIDTH);
        }

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < ambulancia.size(); i++) {
            model.addElement(ambulancia.get(i));
        }
        combo_eliminarambulancias.setModel(model);
        jb_ambulancia.setModel(model);

        ambulancia_placa.setText("");
        ambulancia_año.setText("");
        ambulancia_velocidad.setValue(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int reps = JOptionPane.showConfirmDialog(jpanel_ambulancia, "Desea eliminar esta ambulancia", " Eliminar", WIDTH);
        if (reps == 0) {
            ambulancia.remove(combo_eliminarambulancias.getSelectedIndex());
            JOptionPane.showMessageDialog(jpanel_ambulancia, "Se elimino correctamente.", "Eliminado", reps);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (int i = 0; i < ambulancia.size(); i++) {
                model.addElement(ambulancia.get(i));
            }
            combo_eliminarambulancias.setModel(model);
        } else {
            JOptionPane.showMessageDialog(jpanel_ambulancia, "No se elimino.", "Sin eliminar", reps);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox6.isSelected() == true) {
            agregar_ambulancia.setVisible(true);
            eliminar_ambulancia.setVisible(false);
        } else {
            agregar_ambulancia.setVisible(false);
            eliminar_ambulancia.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox7.isSelected() == true) {
            agregar_ambulancia.setVisible(false);
            eliminar_ambulancia.setVisible(true);
        } else {
            agregar_ambulancia.setVisible(false);
            eliminar_ambulancia.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(complejo_ambulancias.getValue().toString()) > temp_ambulancia.size()) {
            temp_ambulancia.add((Ambulancias) jb_ambulancia.getSelectedItem());
        } else {
            JOptionPane.showMessageDialog(jpanel_complejo, "No se puede agregar porque excede la cantidad de ambulancias", "Error", WIDTH);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbotton_coneccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotton_coneccionActionPerformed
        // TODO add your handling code here:
        jbotton_coneccion.setEnabled(false);
        Conecciones.setVisible(true);
        Conecciones.setTitle("Coneccion");
        Conecciones.pack();
        Conecciones.setResizable(false);
        Imagen Imagen = new Imagen("/Images/conecciones.jpg");
        jpanel_coneccion.add(Imagen);
        jpanel_coneccion.repaint();
        agregar_coneccion.setVisible(false);
        floyd_coneccion.setVisible(false);
        emergencia_coneccion.setVisible(false);
        jbotton_coneccion.setEnabled(true);
    }//GEN-LAST:event_jbotton_coneccionActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(complejo_paramedicos.getValue().toString()) > temp_paramedico.size()) {
            temp_paramedico.add((Paramedicos) jb_paramedicos.getSelectedItem());
        } else {
            JOptionPane.showMessageDialog(jpanel_complejo, "No se puede agregar porque excede la cantidad de paramedicos", "Error", WIDTH);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        grafo.addArista(inicio.getSelectedIndex(), end.getSelectedIndex(), true, Integer.parseInt(peso.getText()));
        JOptionPane.showMessageDialog(jpanel_coneccion, "Se conecto con excito", "Enhorbuena", WIDTH);
        peso.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        grafo.addNodos(numero);
        grafo.setNombreNodo(numero, a_otrolado.getText());
        numero++;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement(grafo.getNombreNodo(numero-1));
        lugar.setModel(model);
        
        grafo.addArista(otro_lado.getSelectedIndex(), numero - 1, true, Integer.parseInt(peso_a.getText()));
        JOptionPane.showMessageDialog(jpanel_coneccion, "Se conecto con excito", "Enhorbuena", WIDTH);
        a_otrolado.setText("");
        peso_a.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox5.isSelected() == true) {
            agregar_coneccion.setVisible(true);
            floyd_coneccion.setVisible(false);
            emergencia_coneccion.setVisible(false);
        } else {
            agregar_coneccion.setVisible(false);
            floyd_coneccion.setVisible(false);
            emergencia_coneccion.setVisible(false);
        }        
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        grafo.ver();
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox9.isSelected() == true) {
            agregar_coneccion.setVisible(false);
            floyd_coneccion.setVisible(true);
            emergencia_coneccion.setVisible(false);
        } else {
            agregar_coneccion.setVisible(false);
            floyd_coneccion.setVisible(false);
            emergencia_coneccion.setVisible(false);
        }
        //txt_floyd.setText(grafo.getfloyd().array.toString());
        int[][] matriz = grafo.getfloyd().array;
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz.length; j++) {
            System.out.println(matriz[i][j]);
        }
        }

    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox10.isSelected() == true) {
            agregar_coneccion.setVisible(false);
            floyd_coneccion.setVisible(false);
            emergencia_coneccion.setVisible(true);
        } else {
            agregar_coneccion.setVisible(false);
            floyd_coneccion.setVisible(false);
            emergencia_coneccion.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(complejo_hospitalario.get(centro_hos.getSelectedIndex()).getParamedicos().size()<3 || !emergencia_ranking.getSelectedItem().toString().contentEquals(complejo_hospitalario.get(centro_hos.getSelectedIndex()).getRanking())){
            JOptionPane.showMessageDialog(jpanel_coneccion,"No se puede enviar desde este centro debido a falta de persional" ,"ERROR", WIDTH);
        }else{
            System.out.println("kjjasdkjkjasdh");
           new Thread(new Hilo(complejo_hospitalario.get(centro_hos.getSelectedIndex()).getParamedicos(),complejo_hospitalario.get(centro_hos.getSelectedIndex()).getAmbulancias().get(0))).start();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Ambulancia;
    private javax.swing.JFrame Complejo;
    private javax.swing.JFrame Conecciones;
    private javax.swing.JFrame Paramedicos;
    private javax.swing.JTextField a_otrolado;
    private javax.swing.JPanel agregar_ambulancia;
    private javax.swing.JPanel agregar_complejo;
    private javax.swing.JPanel agregar_coneccion;
    private javax.swing.JPanel agregar_paramedico;
    private javax.swing.JFormattedTextField ambulancia_año;
    private javax.swing.JTextField ambulancia_placa;
    private javax.swing.JSpinner ambulancia_velocidad;
    private javax.swing.JComboBox centro_hos;
    private javax.swing.JComboBox combo_eliminarambulancias;
    private javax.swing.JComboBox combo_eliminarcomplejo;
    private javax.swing.JComboBox combo_eliminarparamedico;
    private javax.swing.JSpinner complejo_ambulancias;
    private javax.swing.JTextField complejo_direccion;
    private javax.swing.JTextField complejo_nombre;
    private javax.swing.JSpinner complejo_paramedicos;
    private javax.swing.JComboBox complejo_ranking;
    private javax.swing.JPanel eliminar_ambulancia;
    private javax.swing.JPanel eliminar_complejo;
    private javax.swing.JPanel eliminar_paramedico;
    private javax.swing.JPanel emergencia_coneccion;
    private javax.swing.JComboBox emergencia_ranking;
    private javax.swing.JComboBox end;
    private javax.swing.JPanel floyd_coneccion;
    private javax.swing.JComboBox inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jb_ambulancia;
    private javax.swing.JComboBox jb_paramedicos;
    private javax.swing.JButton jbotton_ambulancia;
    private javax.swing.JButton jbotton_complejo;
    private javax.swing.JButton jbotton_coneccion;
    private javax.swing.JButton jbotton_paramedico;
    private javax.swing.JPanel jpanel_ambulancia;
    private javax.swing.JPanel jpanel_complejo;
    private javax.swing.JPanel jpanel_coneccion;
    private javax.swing.JPanel jpanel_entrada;
    private javax.swing.JPanel jpanel_paramedicos;
    private javax.swing.JComboBox lugar;
    private javax.swing.JComboBox otro_lado;
    private javax.swing.JSpinner paramedico_edad;
    private javax.swing.JFormattedTextField paramedico_id;
    private javax.swing.JTextField paramedico_nombre;
    private javax.swing.JComboBox paramedico_ranking;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField peso_a;
    private javax.swing.JTextArea txt_floyd;
    // End of variables declaration//GEN-END:variables
ArrayList<Complejo_Hospitalario> complejo_hospitalario = new ArrayList();
    ArrayList<Paramedicos> paramedicos = new ArrayList();
    ArrayList<Ambulancias> ambulancia = new ArrayList();
    ArrayList<Ambulancias> temp_ambulancia = new ArrayList();
    ArrayList<Paramedicos> temp_paramedico = new ArrayList();
    Grafo grafo = new Grafo();
    int numero = 0;
    int[] nodo;
}
